name: Release (Staging)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      # Install Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Link Supabase project to CLI
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID

      # Push database migrations
      - run: supabase db push
